ORA/ORA/Models/EmployeeProfile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ORA.Models
{
    public class EmployeeProfile
    {
        public int EmployeeId { get; set; }
        public Person EmployeeDetails { get; set; }
        public DailyStatus EmployeeDailyStatus { get; set; }
        public List<Delivery> EmployeeDeliveries { get; set; }
        public int EmployeeDelegationId { get; set; }
        public string EmployeeDelegationName { get; set; }
    }
}

ORA/ORA/Controllers/EmployeeProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ORA.Models;
using Delegate = ORA.Models.Delegate;


namespace ORA.Controllers
{
    public class EmployeeProfileController : Controller
    {
        private readonly ORAContext _context;

        public EmployeeProfileController(ORAContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var employeeProfile = getEmployeeProfile(1);

            return View(employeeProfile);
        }

        public async Task<ActionResult> Edit(int employeeId)
        {
            var employeeProfile = getEmployeeProfile(employeeId);

            return View("EmployeeProfileEdit", employeeProfile);
        }

        public ActionResult New (int employeeId)
        {
            var employeeNewParcel = new Delivery();
            employeeNewParcel.Recipient = employeeId;

            return View("EmployeeParcelAdd", employeeNewParcel);
        }

        public ActionResult Insert(Delivery newDelivery)
        {
            var employeeNewParcel = new Delivery();
            employeeNewParcel.TrackingNumber = newDelivery.TrackingNumber;
            employeeNewParcel.Recipient = newDelivery.Recipient;
            employeeNewParcel.IsDelivered = false;

            try
            {
                _context.Delivery.Add(employeeNewParcel);
                _context.SaveChanges();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }

            var employeeProfile = getEmployeeProfile(newDelivery.Recipient.Value);

            return View("Index", employeeProfile);
        }

        public ActionResult Update(EmployeeProfile employeeProfile)
        {
            var todayDate = System.DateTime.Today.ToShortDateString();
            var employeeDetails = _context.Person.FirstOrDefault(x => x.Id == employeeProfile.EmployeeId);
            employeeDetails.Mobile = employeeProfile.EmployeeDetails.Mobile;
            employeeDetails.Ic = employeeProfile.EmployeeDetails.Ic;

            var delegation = new Delegate()
            {
                PersonId = employeeProfile.EmployeeId,
                DelegatePersonId = employeeProfile.EmployeeDelegationId
            };

            var employeeDailyStatus = new DailyStatus()
            {
                PersonId = employeeProfile.EmployeeId,
                Date = System.DateTime.Today,
                Status = employeeProfile.EmployeeDailyStatus.Status
            };

            try
            {
                _context.Person.Update(employeeDetails);
                _context.DailyStatus.Add(employeeDailyStatus);
                _context.Delegate.Update(delegation);
                _context.SaveChanges();

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }

            var employeeProfileUpdated = getEmployeeProfile(employeeProfile.EmployeeId);

            return View("Index",employeeProfileUpdated);
        }

        private EmployeeProfile getEmployeeProfile(int employeeId)
        {
            var todayDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 0, 0, 0);
            var employeeDetails = _context.Person.FirstOrDefault(x => x.Id == employeeId);
            var employeeDailyStatus = _context.DailyStatus.FirstOrDefault(x => x.Id == employeeId && x.Date == todayDate);
            var employeeDeliveries = new List<Delivery>();
            var deliveries = _context.Delivery.Where(x => x.Recipient == employeeId);
            foreach (var delivery in deliveries)
            {
                employeeDeliveries.Add(delivery);
            }

            var delegations = _context.Delegate.Where(x => x.PersonId == employeeId).Select(y => y.DelegatePersonId).Last();
            var employeeDelegationName = getEmployeeName(delegations.Value);
            var employeeDelegationId = delegations.Value;

            var employeeProfile = new EmployeeProfile()
            {
                EmployeeId = employeeId,
                EmployeeDetails = employeeDetails,
                EmployeeDailyStatus = employeeDailyStatus,
                EmployeeDeliveries = employeeDeliveries,
                EmployeeDelegationId = employeeDelegationId,
                EmployeeDelegationName = employeeDelegationName
            };
            return employeeProfile;
        }

        private string getEmployeeName(int employeeId)
        {
            var employeeName = _context.Person.FirstOrDefault(x => x.Id == employeeId).Name;
            return employeeName;
        }
    }
}

ORA/ORA/Views/EmployeeProfile/EmployeeParcelAdd.cshtml
@model ORA.Models.Delivery

@{
    ViewData["Title"] = "New Parcel";
}
@using (Html.BeginForm("Insert", "EmployeeProfileController", FormMethod.Post))
{
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h2>New Parcel</h2>
            </div>
            <div class="col-lg-10 mx-auto">
                <div class="form-group">
                    <label for="visitorName">Parcel ID :</label>
                    @Html.TextBoxFor(m => m.TrackingNumber)
                </div>
                <div class="form-group" style="visibility: hidden">

                    @Html.TextBoxFor(m => m.Recipient)
                </div>
            </div>
            <div class="col-lg-10 mx-auto" style="text-align: left">
                <button class="btn btn-primary btn-lg js-scroll-trigger" style="font-size: 20px; width: 300px"
                        asp-action="Insert" type="submit" class="btn btn-primary" value="Insert">
                    Insert
                </button>
                
                <a class="btn btn-primary btn-lg js-scroll-trigger" style="font-size: 20px; width: 300px" asp-area="" 
                   asp-controller="EmployeeProfile" asp-action="Index">Cancel</a>

            </div>
        </div>
    </div>
}
    @*@using (Html.BeginForm("Insert", "EmployeeProfileController", FormMethod.Post))
        {
            <table>
                <tr>
                    <td>Parcel ID :</td>
                    <td>@Html.TextBoxFor(m => m.TrackingNumber)</td>
                </tr>
                <tr>
                    <td></td>
                </tr>
                <tr>
                    <td colspan="2">
                        <input type="hidden" name="EmployeeId" value="@Model.Recipient" />
                        <input type="submit" value="Save"
                               formaction="Insert" />
                        <input type="submit" value="Cancel"
                               formaction="Index" />
                    </td>
                </tr>
            </table>
        }*@

ORA/ORA/Views/EmployeeProfile/EmployeeProfileEdit.cshtml
@model ORA.Models.EmployeeProfile

@{
    ViewData["Title"] = "Employee Profile Update";
}
@using (Html.BeginForm("Update", "EmployeeProfileController", FormMethod.Post))
{
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h2>Employee Profile</h2>
            </div>
            <div class="col-lg-10 mx-auto">
                <div class="form-group">
                    <label for="visitorName">Employee Mobile : </label>
                    @Html.EditorFor(model => model.EmployeeDetails.Mobile)
                </div>
                <div class="form-group">
                    <label for="visitorName">Employee IC Number : </label>
                    @Html.EditorFor(model => model.EmployeeDetails.Ic)
                </div>
                <div class="form-group">
                    <label for="visitorName">Employee Status : </label>
                    @* @Html.EditorFor(model => model.EmployeeDailyStatus.Status)*@

                    @{
                        var listItems = new List<SelectListItem>();
                        listItems.Add(new SelectListItem { Text = "On Leave", Value = "0" });
                        listItems.Add(new SelectListItem { Text = "In Office", Value = "1" });
                        listItems.Add(new SelectListItem { Text = "Work From Home", Value = "2" });
                    }

                    @Html.DropDownListFor(model => model.EmployeeDailyStatus.Status, listItems)

                </div>
                <div class="form-group">
                    <label for="usr">Delegation :</label>
                    <input list="usrlist" type="text" class="form-control" id="usr">
                    <datalist id="usrlist"></datalist>
                    <input type="hidden" name="answer" id="usr-hidden">
                    <input type="hidden" name="EmployeeDelegationId" id="EmployeeDelegationId">
                </div>
            </div>
            <div class="col-lg-10 mx-auto" style="text-align: left">
                @Html.HiddenFor(model => model.EmployeeDelegationId)
                <input type="hidden" name="EmployeeId" value="@Model.EmployeeId" />
                <input class="btn btn-primary btn-lg js-scroll-trigger" style="font-size: 20px; width: 300px"
                       type="submit" value="Save" formaction="Update" />
                <a class="btn btn-primary btn-lg js-scroll-trigger" style="font-size: 20px; width: 300px" asp-area="" asp-controller="EmployeeProfile" asp-action="Index">Cancel</a>
            </div>
        </div>
    </div>
}

@section Scripts
    {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script>
        $(document).ready(function () {
            $.ajax({
                type: 'GET',
                url: '/api/Person',
                success: function (response) {
                    $.each(response,
                        function (key, value) {
                            $('#usrlist').append($('<option>').text(value.name).attr('data-value', value.id));
                        });
                }
            });

            document.querySelector('input[list]').addEventListener('input',
                function (e) {
                    var input = e.target,
                        list = input.getAttribute('list'),
                        options = document.querySelectorAll('#' + list + ' option'),
                        hiddenInput = document.getElementById(input.id + '-hidden'),
                        inputValue = input.value;

                    hiddenInput.value = inputValue;

                    for (var i = 0; i < options.length; i++) {
                        var option = options[i];

                        if (option.innerText === inputValue) {
                            hiddenInput.value = option.getAttribute('data-value');
                            document.getElementById('EmployeeDelegationId').value = hiddenInput.value;
                            break;
                        }
                    }
                });
        });

    </script>
}

ORA/ORA/Views/EmployeeProfile/Index.cshtml
@model ORA.Models.EmployeeProfile

@{
    ViewData["Title"] = "Index";
}

<div class="container my-auto">
    <div class="row">
        <div class="col-lg-10 mx-auto">
            <h2>Employee Profile</h2>
        </div>
        <div class="col-lg-10 mx-auto">
            <div class="form-group">
                <label for="visitorName">Employee Name : </label>
                @Html.DisplayFor(model => model.EmployeeDetails.Name)
            </div>
            <div class="form-group">
                <label for="visitorName">Employee Mobile : </label>
                @Html.DisplayFor(model => model.EmployeeDetails.Mobile)
            </div>
            <div class="form-group">
                <label for="visitorName">Employee IC Number : </label>
                @Html.DisplayFor(model => model.EmployeeDetails.Ic)
            </div>
            <div class="form-group">
                <label for="visitorName">Employee Status : </label>
                @{
                    var status = "";
                    if (Model.EmployeeDailyStatus.Status == "0")
                    {
                        status = "On Leave";

                    }
                    else if (Model.EmployeeDailyStatus.Status == "1")
                    {
                        status = "In Office";
                    }
                    else if (Model.EmployeeDailyStatus.Status == "2")
                    {
                        status = "Work From Home";
                    }
                }
                @Html.Label(status)
            </div>
            <div class="form-group">
                <label for="visitorName">Delegation : </label>
                @Html.DisplayFor(model => model.EmployeeDelegationName)
            </div>

        </div>
        <div class="col-lg-10 mx-auto" style="text-align: left">
        @using (Html.BeginForm("Edit", "EmployeeProfileController", FormMethod.Post))
        {
            <input type="hidden" name="EmployeeId" value="@Model.EmployeeId"/>
            <button class="btn btn-primary btn-lg js-scroll-trigger" style="font-size: 20px; width: 300px" 
                    asp-action="Edit" type="submit" class="btn btn-primary" value="Edit">Edit Profile</button>
        }
        </div>

        <br /><br /><br />

        @Html.Partial("~/Views/EmployeeProfile/_EmployeeParcel.cshtml", Model)
        <div class="col-lg-10 mx-auto" style="text-align: left">
        @using (Html.BeginForm("New", "EmployeeProfileController", FormMethod.Post))
        {
            <input type="hidden" name="EmployeeId" value="@Model.EmployeeId"/>
            <button class="btn btn-primary btn-lg js-scroll-trigger" style="font-size: 20px; width: 300px"
                    asp-action="New" type="submit" class="btn btn-primary" value="New">New</button>
        }
        </div>
        @*<p>
            @Html.DisplayFor(model => model.EmployeeDetails.Name)
        </p>
        <p>
            @Html.DisplayFor(model => model.EmployeeDetails.Mobile)
        </p>
        <p>
            @Html.DisplayFor(model => model.EmployeeDetails.Ic)
        </p>
        <p>
            @Html.DisplayFor(model => model.EmployeeDailyStatus.Status)
        </p>*@
        @*@using (Html.BeginForm("Edit", "EmployeeProfileController", FormMethod.Post))
        {
            <span>
                <input type="hidden" name="EmployeeId" value="@Model.EmployeeId" />
                <button asp-action="Edit" type="submit" class="btn btn-primary" value="Edit">Edit Profile</button>
            </span>
        }*@
        @*<br /><br />
        <br />
        @Html.Partial("~/Views/EmployeeProfile/_EmployeeParcel.cshtml", Model)
        @using (Html.BeginForm("New", "EmployeeProfileController", FormMethod.Post))
        {
            <span>
                <input type="hidden" name="EmployeeId" value="@Model.EmployeeId" />
                <button asp-action="New" type="submit" class="btn btn-primary" value="New">New</button>
            </span>
        }*@
    </div>
</div>

ORA/ORA/Views/EmployeeProfile/_EmployeeParcel.cshtml
@model ORA.Models.EmployeeProfile

<div class="container my-auto">
    <div class="row">
        <div class="col-lg-10 mx-auto">
            <h2>Parcel List</h2>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th>
                    Items
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.EmployeeDeliveries)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TrackingNumber)
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>