ORA/ORA/Controllers/KioskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ORA.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ORA.Controllers
{
    public class KioskController : Controller
    {
        private readonly ORAContext _context;

        public KioskController(ORAContext context)
        {
            _context = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Parcel()
        {
            //ParcelOrder order = new ParcelOrder();
            //order.Deliveries = await _context.Delivery.ToListAsync();
            //order.People = await _context.Person.ToListAsync();

            return View(await _context.Delivery.ToListAsync());
        }

        public IActionResult AcceptParcel()
        {
            return View();
        }

        [Route("Timer/{userId}/{deliveryId}")]
        public async Task<IActionResult> Timer(int userId, int deliveryId)
        {
            ViewData["userId"] = userId;
            ViewData["deliveryId"] = deliveryId;

            MSTeamsController team = new MSTeamsController(_context);
            await team.PostMSTeam(deliveryId);

            return View();
        }

        [Route("TimeOut/{deliveryId}/{userId}")]
        public IActionResult TimeOut(int deliveryId, int userId)
        {
            ViewData["userId"] = userId;
            ViewData["deliveryId"] = deliveryId;

            return View();
        }
        public IActionResult Receive()
        {
            return View();
        }

        [Route("Reveal/{userId}/{deliveryId}")]
        public IActionResult Reveal(int userId, int deliveryId)
        {
            ViewData["userId"] = userId;
            ViewData["deliveryId"] = deliveryId;

            return View(_context.Person.SingleOrDefault(x => x.Id.Equals(userId)));
        }
    }
}

ORA/ORA/Controllers/VisitorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ORA.Models;
using System.Net.Http;

namespace ORA.Controllers
{
    public class VisitorController : Controller
    {
        private readonly ORAContext _context;

        public VisitorController(ORAContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var visitors = _context.VisitorLogBook.ToList();
            var visitorList = new List<EmployeeVisitor>();
            foreach (var visitor in visitors)
            {
                visitorList.Add(new EmployeeVisitor()
                {
                    EmployeeName = getEmployeeName(visitor.PersonId.Value),
                    VisitorLogBook = visitor
                });   
            }
            
            return View(visitorList);
        }

        public void PostMSTeamVisitor(int id)
        {
            var visitor = _context.VisitorLogBook.SingleOrDefault(m => m.Id == id);

            if (visitor != null)
            {
                var person = _context.Person.SingleOrDefault(m => m.Id == visitor.PersonId);

                //MS Teams card template - load from txt file
                string contents = System.IO.File.ReadAllText(@"cardVisitor.txt");

                //parameters sent from kiosk api
                string name = person.Name;
                string visitorName = visitor.VisitorName;

                //end


                contents = contents.Replace("{@name}", name).Replace("{@visitorName}", visitorName);

                var client = new HttpClient();
                var url = @"https://outlook.office.com/webhook/f54e79a0-3e9c-41eb-b2cb-1e32b75700e5@1ca8bd94-3c97-4fc6-8955-bad266b43f0b/IncomingWebhook/3b41df005c4745bc8062e1b4cbddba88/27104d89-4f76-412d-9bf9-933a678624bc";
                //ConfigurationManager.AppSettings["incomingWebhook"];
                //var bodyzz = @"\";
                // var message = "{\"text\": \"" + bodyzz + "\"}";
                var message = contents;
                var body = new StringContent(message, System.Text.Encoding.UTF8, "application/json");
                var result = client.PostAsync(url, body);//
            }
        }


        public ActionResult Insert(VisitorLogBook visitorLogBook)
        {
            try
            {
                _context.VisitorLogBook.Add(visitorLogBook);
                _context.SaveChanges();

                var id = _context.VisitorLogBook.OrderByDescending(x => x.Id).First().Id;
               PostMSTeamVisitor(id);

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }

            //var visitors = _context.VisitorLogBook.ToList();
            //var visitorList = new List<EmployeeVisitor>();
            //foreach (var visitor in visitors)
            //{
            //    visitorList.Add(new EmployeeVisitor()
            //    {
            //        EmployeeName = getEmployeeName(visitor.PersonId.Value),
            //        VisitorLogBook = visitor
            //    });   
            //}
           

           return View("~/Views/Kiosk/Index.cshtml");
        }

        public ActionResult New()
        {
            return View("VisitorRegister");
        }

        private string getEmployeeName(int employeeId)
        {
            var employeeName = _context.Person.FirstOrDefault(x => x.Id == employeeId).Name;
            return employeeName;
        }
    }
}

ORA/ORA/Views/Kiosk/AcceptParcel.cshtml
<div class="container my-auto" id="result" >
    <div class="row">
        <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase text-center">
                <strong>ARVATO SYSTEMS OFFICE RECEPTION ASSISTANT</strong>
            </h1>
            <hr>
        </div>
        <div class="col-lg-10 mx-auto" style="text-align:center; font-size:30px" id="txtMessage">

            <hr>
        </div>
        <br />
        <div class="col-lg-10 mx-auto" style="text-align:center">
            <a class="btn btn-primary btn-lg js-scroll-trigger" style="font-size:20px; width:300px" onclick="window.close()">Close</a>
        </div>
    </div>
</div>

<div class="container my-auto" id="main" >
    <div class="row">
        <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase text-center">
                <strong>ARVATO SYSTEMS OFFICE RECEPTION ASSISTANT</strong>
            </h1>
            <hr>
        </div>
        <div class="col-lg-10 mx-auto" style="text-align:center; font-size:30px" id="txtMessage">

            <hr>
        </div>
        <br />
        <div class="col-lg-10 mx-auto" style="text-align:center">
            <a class="btn btn-primary btn-lg js-scroll-trigger" style="font-size:20px; width:300px" onclick="accept()">Pick Up</a>          
            <a class="btn btn-primary btn-lg js-scroll-trigger" style="font-size:20px; width:300px" onclick="window.close()">Close</a>
        </div>
    </div>
</div>


<script src="~/lib/jquery/dist/jquery.min.js"></script>

<script>

    
    
    function GetParameterValues(param) {
        var url = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
        for (var i = 0; i < url.length; i++) {
            var urlparam = url[i].split('=');
            if (urlparam[0] == param) {
                return urlparam[1];
            }
        }
    }  

    $(document).ready(function () {
        $("#result").hide();
        $("#main").hide();
        var id = GetParameterValues('id');

        var options = {};
        options.url = "/api/Deliveries/getdeliverystatus/" + id;
        options.type = "GET";
        options.dataType = "json";
        options.success = function (data) {
            if (data != "") {//already pickup
                $("#txtMessage").append("<h3>Parcel was picked up by " + data + "</h3>");
                $("#result").show();
                $("#main").hide();
            }
            else {
                $("#main").show();
                $("#result").hide();
            }
        };
        options.error = function () {
            //$("#msg").html("Error while calling the Web API!");
        };
        $.ajax(options);
    });

    function accept() {
        var id = GetParameterValues('id');

        var options = {};
        options.url = "/api/Deliveries/acceptparcel/" + id;
        options.type = "POST";
        options.dataType = "json";
      
        options.success = function (data) {
            if (data != "") {//already pickup
                $("#txtMessage").append("<h3>" + data + "</h3>");
                $("#result").show();
                $("#main").hide();
            }
            else {
                $("#txtMessage").append("<h3> Please pick up now </h3>");
                $("#result").show();
                $("#main").hide();
                setTimeout(function () { window.close(); }, 3000);
            }
        };
        options.error = function () {
            //$("#msg").html("Error while calling the Web API!");
        };
        $.ajax(options); 
    }


</script>

ORA/ORA/Views/Kiosk/Index.cshtml
<div class="container my-auto">
    <div class="row">
        <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase text-center">
                <strong>ARVATO SYSTEMS OFFICE RECEPTION ASSISTANT</strong>
            </h1>
            <hr>
        </div>
        <div class="col-lg-10 mx-auto" style="text-align:center; font-size:30px">
            <p class="text-faded mb-5" >Kindly choose your favourite!</p>
            <hr>
        </div>
        <div class="col-lg-10 mx-auto" style="text-align:center">
            <a class="btn btn-primary btn-block" style="font-size:50px" asp-area="" asp-controller="Kiosk" asp-action="Parcel">Deliver Parcel</a>
        </div>
        <div class="col-lg-10 mx-auto">
            <br />
            <br />
            <br />
        </div>
        <div class="col-lg-10 mx-auto" style="text-align:center">
            @*<a class="btn btn-primary btn-lg js-scroll-trigger" style="font-size:50px; width:500px"  asp-area="" asp-controller="Visitor" asp-action="Index">Visitor</a>*@
            <a class="btn btn-primary btn-block" style="font-size:50px;" asp-area="" asp-controller="Visitor" asp-action="New">Register</a>
        </div>
    </div>
</div>

ORA/ORA/Views/Kiosk/Parcel.cshtml
@model List<ORA.Models.Delivery>

<div class="container my-auto">
    <div class="row">
        <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase text-center">
                <strong>ARVATO SYSTEMS OFFICE RECEPTION ASSISTANT</strong>
            </h1>
            <hr>
        </div>
        <div class="col-lg-10 mx-auto">
            <form>
                <div class="form-group">
                    <label for="usr">Recipient:</label>
                    <input list="usrlist" type="text" class="form-control" id="usr">
                    <datalist id="usrlist"></datalist>
                    <input type="hidden" name="answer" id="usr-hidden">
                </div>
                <div class="form-group">
                    <label for="pwd">Parcel Tracking Number:</label>
                    <input type="text" class="form-control" id="pwd">
                </div>
            </form>
        </div>
        <div class="col-lg-10 mx-auto" style="text-align:center">
            <a class="btn btn-primary btn-lg js-scroll-trigger" style="font-size:20px; width:300px" onclick="CheckDelivery()">Submit</a>
            <a class="btn btn-primary btn-lg js-scroll-trigger" style="font-size:20px; width:300px" asp-area="" asp-controller="Kiosk" asp-action="Index">Back to Home</a>
        </div>

        <br />
        <div id="errMsg" class="col-lg-10 mx-auto alert alert-danger" style="display:none">
        </div>        
    </div>
</div>

@section Scripts {

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script>
        $(document).ready(function () {
            $.ajax({
                type: 'GET',
                url: '/api/Person',
                success: function (response) {
                    $.each(response, function (key, value) {
                        $('#usrlist').append($('<option>').text(value.name).attr('data-value', value.id));
                    });
                }
            });

            document.querySelector('input[list]').addEventListener('input', function (e) {
                var input = e.target,
                    list = input.getAttribute('list'),
                    options = document.querySelectorAll('#' + list + ' option'),
                    hiddenInput = document.getElementById(input.id + '-hidden'),
                    inputValue = input.value;

                hiddenInput.value = inputValue;

                for (var i = 0; i < options.length; i++) {
                    var option = options[i];

                    if (option.innerText === inputValue) {
                        hiddenInput.value = option.getAttribute('data-value');
                        break;
                    }
                }
            });
        });

        function CheckDelivery() {
            var userId = $('#usr-hidden').val();
            var parcelNo = $('#pwd').val();

            $.ajax({
                type: 'POST',
                url: '/api/Person/GetPerson/' + userId + '/' + parcelNo,
                success: function (response) {
                    var link = '@(Url.Action("Timer", "Kiosk", new { userId = "replaceId", deliveryId = "replacedId" }))';
                    link = link.replace("replaceId", response.recipient);
                    link = link.replace("replacedId", response.id);

                    window.location.href = link;
                },
                error: function (response) {
                    var json = $.parseJSON(response.responseText);
                    $('#errMsg').css("display", "block");
                    $('#errMsg').text(json.errorMsg);
                }
            });
        }
    </script>

}

ORA/ORA/Views/Kiosk/Receive.cshtml
<div class="container my-auto">
    <div class="row">
        <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase text-center">
                <strong>ARVATO SYSTEMS OFFICE RECEPTION ASSISTANT</strong>
            </h1>
            <hr>
        </div>
        <div class="col-lg-10 mx-auto" style="text-align:center; font-size:20px">
            <p>Thanks for waiting, the parcel recipient is on the way coming to collect.</p>
            <hr>
        </div>
        <div class="col-lg-10 mx-auto" style="text-align:center">
            <a class="btn btn-primary btn-lg js-scroll-trigger" style="font-size:20px; width:300px" asp-area="" asp-controller="Kiosk" asp-action="Index">OK</a>
        </div>
    </div>
</div>

ORA/ORA/Views/Kiosk/Reveal.cshtml
@model ORA.Models.Person

<div class="container my-auto">
    <div class="row">
        <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase text-center">
                <strong>ARVATO SYSTEMS OFFICE RECEPTION ASSISTANT</strong>
            </h1>
            <hr>
        </div>
        <div class="col-lg-10 mx-auto" style="text-align:center; font-size:20px">
            <p>Here is the receipiant IC/Passport Number:</p>
            <h1>@Model.Ic</h1>
            <hr>
        </div>
        <div class="col-lg-10 mx-auto" style="text-align:center; font-size:20px">
            <p>Here is the receipiant phone Number:</p>
            <h1>@Model.Mobile</h1>
            <hr>
        </div>
        <div class="col-lg-10 mx-auto" style="text-align:center">
            <a class="btn btn-primary btn-lg js-scroll-trigger" style="font-size:20px; width:300px" onclick="UpdateDelivery()">OK</a>
            <a class="btn btn-primary btn-lg js-scroll-trigger" style="font-size: 20px; width: 300px" asp-area=""
               asp-controller="Kiosk" asp-action="Index">Back to Home</a>
        </div>

        <br />
        <div id="errMsg" class="col-lg-10 mx-auto alert alert-danger" style="display:none">
        </div>
        <div id="Msg" class="col-lg-10 mx-auto alert alert-success" style="display:none">
        </div>
    </div>
</div>

@section Scripts {

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script>
        function UpdateDelivery() {
            var userId = @ViewData["userId"];
            var deliveryId = @ViewData["deliveryId"];

            $.ajax({
                type: 'POST',
                url: '/api/Deliveries/AcceptParcelByIC/' + deliveryId + '/' + userId,
                success: function (response) {
                    //var json = $.parseJSON(response);
                    $('#Msg').css("display", "block");
                    $('#Msg').append(response.msg);

                    setTimeout("location.href = '/Kiosk/Index';", 10000);
                },
                error: function (response) {
                    var json = $.parseJSON(response.responseText);
                    $('#errMsg').css("display", "block");
                    $('#errMsg').text(json.errorMsg);
                }
            });
        }
    </script>

}

ORA/ORA/Views/Kiosk/TimeOut.cshtml
<div class="container my-auto">
    <div class="row">
        <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase text-center">
                <strong>ARVATO SYSTEMS OFFICE RECEPTION ASSISTANT</strong>
            </h1>
            <hr>
        </div>
        <div class="col-lg-10 mx-auto" style="text-align:center; font-size:20px">
            <p>Please get the receptionist or employee to insert below credential for retrieving recipient's IC/Passport number for your signing certificate.</p>
            <hr>
        </div>
        <div class="col-lg-10 mx-auto">
            <form>
                <div class="form-group">
                    <label for="pwd">consignee email:</label>
                    <input type="text" class="form-control" id="email">
                </div>
            </form>
        </div>
        <div class="col-lg-10 mx-auto" style="text-align:center">
            <a class="btn btn-primary btn-lg js-scroll-trigger" style="font-size:20px; width:300px" id="say_hello" onclick="Reveal()">Submit</a>
            <a class="btn btn-primary btn-lg js-scroll-trigger" style="font-size:20px; width:300px" asp-area="" asp-controller="Kiosk" asp-action="Index">Cancel</a>
        </div>

        <br />
        <div id="errMsg" class="col-lg-10 mx-auto alert alert-danger" style="display:none">
        </div>
    </div>
</div>

@section Scripts {

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script>   
        function Reveal() {
            var userId = @ViewData["userId"];              
            var deliveryId = @ViewData["deliveryId"]; 
            var email = $('#email').val();

            $.ajax({
                type: 'GET',
                url: '/api/Person/GetPersonICByEmail/' + email + '/' + deliveryId + '/' + userId,
                success: function (response) {
                    var link = '@(Url.Action("Reveal", "Kiosk", new { deliveryId = "replaceId", userId = "replacedId" }))';
                    link = link.replace("replacedId", response.id);
                    link = link.replace("replaceId", deliveryId);

                    window.location.href = link;
                },
                error: function (response) {
                    var json = $.parseJSON(response.responseText);
                    $('#errMsg').css("display", "block");
                    $('#errMsg').text(json.errorMsg);
                }
            });
        }
    </script>

}

ORA/ORA/Views/Kiosk/Timer.cshtml
<div class="container my-auto">
    <div class="row">
        <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase text-center">
                <strong>ARVATO SYSTEMS OFFICE RECEPTION ASSISTANT</strong>
            </h1>
            <hr>
        </div>
        <div class="col-lg-10 mx-auto" style="text-align:center; font-size:30px">
            <p>Please wait for the recipient response within 1 minute.</p>
            <hr>
        </div>
        <div class="col-lg-10 mx-auto">
            <div id="timer" style="color:red; font-size:200px; text-align:center">1:00</div>
        </div>
    </div>
</div>


<script type="text/javascript">

    var timeoutHandle;
    function countdown(minutes) {
        var seconds = 60;
        var mins = minutes
        function tick() {
            var counter = document.getElementById("timer");
            var current_minutes = mins - 1
            seconds--;
            counter.innerHTML =
                current_minutes.toString() + ":" + (seconds < 10 ? "0" : "") + String(seconds);
            if (seconds > 0) {
                timeoutHandle = setTimeout(tick, 1000);
            } else {          
                if (mins > 1) {
                    setTimeout(function () { countdown(mins - 1); }, 1000);
                }
                else if (seconds === 0) {
                    var userId = @ViewData["userId"];              
                    var deliveryId = @ViewData["deliveryId"];                    

                    var link = '@(Url.Action("TimeOut", "Kiosk", new { deliveryId = "replaceId", userId = "replaceuserId" }))';
                    link = link.replace("replaceId", deliveryId);
                    link = link.replace("replaceuserId", userId);
                    window.location.href = link;
                }
            }
        }
        tick();
    }

    countdown(1);

    var myVar = setInterval(getStatus, 3000);
    
    function getStatus() {

        var deliveryId = @ViewData["deliveryId"]

        var options = {};
        options.url = "/api/Deliveries/getdeliverystatus/" + deliveryId;
        options.type = "GET";
        options.dataType = "json";
        options.success = function (data) {
            if (data !== "") {//already pickup
                clearInterval(myVar);
                window.location.href = '@(Url.Action("Receive", "Kiosk"))';
            }
        };
        options.error = function () {
            //$("#msg").html("Error while calling the Web API!");
        };
        $.ajax(options);

    }


</script>